#+TITLE: LaTeX-Templates

In this repository I collect LaTeX templates, styles and classes I develop
or use frequently. If I am not the author, this will be noted.

* Installation
** Classes and Styles
*** From source (recomended)
If the class is not uploaded to CTAN (I want to upload and update
them all to CTAN, but I it may take some time), clone the repository
into a directory searched by LaTeX. (Using TexLive under Linux this
directory could be `~/texmf/tex/latex`, using MikTeX under Windows,
this is configurable) and index them (TexLive+Linux: `$ texhash`,
MikTeX+Windows: Refresh the sources via the MikTeX settings as
Admin).
**** Special notes on development versions:
Pulling a development version might not include a built version of the cls/sty
files. Run the build script available to build the cls file as well as fresh documentation.

* homeworkassignment (LaTeX)
This class provides a relatively simple document–type for homework,
mainly created for assignments at the University during my studies in
Computer Science. 

It features an easy to use sectioning, frequently used packages and
configurations and macros fo mathematical functions and operators,
which I need often.

* cheatsheet (LaTeX)
I figured that the sourcecode of Cheat-Sheets in LaTeX is always a
hughe pile of badly documented code, which is basically identical for
all CheatSheets, so I bundeled it in a class. Just load
=\documentclass{cheatsheet}= and you are ready to go.

Available on CTAN

* beamer themes =projektion= and =polynom= (XeLaTeX)
Clean, simple and modern 16:9 (yes, that is possible) (Xe)LaTeX
beamer themes.

They are developed to match PowerPoint-Templates by Alexander
Bartolomey Git[[https://git.rwth-aachen.de/occloxium][Lab]] / [[https://github.com/Occloxium][Hub]].
